"""add_hardware_inventory_tables

Revision ID: 3838d8e1c37a
Revises: db5b184a8231
Create Date: 2026-07-14 21:30:57.166636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3838d8e1c37a'
down_revision = 'db5b184a8231'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_installed_software',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('install_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_installed_software_name'), 'device_installed_software', ['name'], unique=False)
    op.create_table('device_inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('computer_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('bios_version', sa.String(length=100), nullable=True),
    sa.Column('motherboard', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('workgroup', sa.String(length=255), nullable=True),
    sa.Column('os_name', sa.String(length=100), nullable=True),
    sa.Column('os_edition', sa.String(length=100), nullable=True),
    sa.Column('os_build', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('os_install_date', sa.DateTime(), nullable=True),
    sa.Column('os_last_boot', sa.DateTime(), nullable=True),
    sa.Column('os_timezone', sa.String(length=100), nullable=True),
    sa.Column('antivirus', sa.String(length=255), nullable=True),
    sa.Column('bitlocker_status', sa.String(length=100), nullable=True),
    sa.Column('firewall_status', sa.String(length=100), nullable=True),
    sa.Column('uptime', sa.String(length=100), nullable=True),
    sa.Column('raw_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('device_inventory_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_memory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('total_ram_bytes', sa.Integer(), nullable=True),
    sa.Column('available_ram_bytes', sa.Integer(), nullable=True),
    sa.Column('memory_slots', sa.Integer(), nullable=True),
    sa.Column('ram_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_network_interfaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('interface_name', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('ip_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dns_servers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gateway', sa.String(length=45), nullable=True),
    sa.Column('dhcp_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_processors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('processor_name', sa.String(length=255), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('logical_processors', sa.Integer(), nullable=True),
    sa.Column('current_speed_mhz', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_services_name'), 'device_services', ['name'], unique=False)
    op.create_table('device_storage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('disk_model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('capacity_bytes', sa.Integer(), nullable=True),
    sa.Column('free_space_bytes', sa.Integer(), nullable=True),
    sa.Column('partitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_storage')
    op.drop_index(op.f('ix_device_services_name'), table_name='device_services')
    op.drop_table('device_services')
    op.drop_table('device_processors')
    op.drop_table('device_network_interfaces')
    op.drop_table('device_memory')
    op.drop_table('device_inventory_history')
    op.drop_table('device_inventory')
    op.drop_index(op.f('ix_device_installed_software_name'), table_name='device_installed_software')
    op.drop_table('device_installed_software')
    # ### end Alembic commands ###
